// components/AdminLayout.js
import ReduxProvider from "@/redux/Provider";
import { Poppins } from "next/font/google";
import { Metadata } from "next";

const poppins = Poppins({
  subsets: ['latin-ext'],
  weight: "300",
  style: "italic"
});

export const metadata: Metadata = {
  title: "Toki Cinema",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReduxProvider>
          <div className="container mx-auto">
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
